spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://u5jnskhfiifthdps:h5LQWD2jR9kmmkb5IYyT@brirymivcsra2dcbkly2-mysql.services.clever-cloud.com:3306/brirymivcsra2dcbkly2?useSSL=true&requireSSL=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:u5jnskhfiifthdps}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:h5LQWD2jR9kmmkb5IYyT}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

server.tomcat.use-relative-redirects=true

# Limit connection pool size
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000